### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [TeamAmaze/FilePreloaderLibrary#18]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by EmmanuelMess** [comment]
No problem!

**Comment by mansya** [comment]
I have designed the logo for this project. What do you think ? do you like it ? if yes please inform me. and let me know if there is a change.
![file preloader library](https://user-images.githubusercontent.com/33461607/47954929-12184f80-dfc3-11e8-8859-5bfb891a4050.png)

for the outer frame I designed with a mother-style edge so that this logo looks attractive. the outer frame is the type of file icon. and for circles in meaning the preloader icon. I combine the two so that this logo is interesting and matches the name of the project.

**Comment by EmmanuelMess** [comment]
2 seems really nice. @VishalNehra what do you think?

**Comment by mansya** [comment]
What do you think sir @VishalNehra ?

**Comment by VishalNehra** [comment]
Sorry but I'm not in vote for changing icon for Amaze atm.
Doesn't mean your icons are bad, it's just that Amaze is well known now, partially because of it's icon, changing it will loose it's identity. Atleast according to me.

**Comment by mansya** [comment]
I have seen your project. is this icon do you mean already more familiar with its identity?
![1](https://user-images.githubusercontent.com/33461607/48016578-8affde80-e15e-11e8-8d94-2c39f4886bb8.png)

**Comment by VishalNehra** [comment]
Ahh, I didn't notice this is about a different repo, and not Amaze. My bad.
Anyways, I'm not sure if this project is a library or a plugin. @EmmanuelMess maybe you can shed some light, then we can move over to choosing an icon.

**Comment by EmmanuelMess** [comment]
It's a library.

**Comment by EmmanuelMess** [comment]
I was thinking of using the icon as [Glide](https://github.com/bumptech/glide) uses theirs.

**Comment by mansya** [comment]
So how ? Is this logo that I offer acceptable?

**Comment by EmmanuelMess** [comment]
Yes.

**Comment by mansya** [comment]
i will give bitmap and vectors sir.

**Comment by mansya** [comment]
I have sent you (**Pull requests**)[https://github.com/TeamAmaze/FilePreloaderLibrary/pull/19]. please check. and I have uploaded all the files to the (**Drive**)[https://drive.google.com/open?id=1c_Mv9w-e1CKvGHpB9L7a5Y_zFBJD37tR]

**Comment by mansya** [comment]
hi sir. I have composed the file into vector format. please check.

**Comment by mansya** [comment]
hi sir. I have changed the image format in the readme to svg. please check the pull requests

**Comment by EmmanuelMess** [comment]
Thanks! Added in #22
